/**
 * This file was automatically generated by the Stencil React Output Target.
 * Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
 */
import type { EventName, StencilReactComponent } from '@stencil/react-output-target/runtime';
import { type ActiveWorkspaceChangeEvent, type EditorIsReadyEvent, type IKritzelDialogCloseEvent, type IKritzelIsPublicChangedEvent, type IKritzelMasterDetailSelectEvent, type KritzelBackToContentCustomEvent, type KritzelBaseObject, type KritzelButtonCustomEvent, type KritzelDialogCustomEvent, type KritzelEditorCustomEvent, type KritzelExportCustomEvent, type KritzelInputCustomEvent, type KritzelLineEndingsCustomEvent, type KritzelLoginDialogCustomEvent, type KritzelMasterDetailCustomEvent, type KritzelNumericInputCustomEvent, type KritzelOpacitySliderCustomEvent, type KritzelPillTabsCustomEvent, type KritzelSettingsConfig, type KritzelSettingsCustomEvent, type KritzelUndoState, type KritzelViewportState, type LineArrowConfig, type LoginEvent, type ObjectsAddedEvent, type ObjectsRemovedEvent, type ObjectsUpdatedEvent, type ThemeName } from "../../../../kritzel-stencil";
import type { Components } from "../../../../kritzel-stencil/dist/components";
import { KritzelAwarenessCursors as KritzelAwarenessCursorsElement } from "../../../../kritzel-stencil/dist/components/kritzel-awareness-cursors.js";
import { KritzelBackToContent as KritzelBackToContentElement } from "../../../../kritzel-stencil/dist/components/kritzel-back-to-content.js";
import { KritzelButton as KritzelButtonElement } from "../../../../kritzel-stencil/dist/components/kritzel-button.js";
import { KritzelCurrentUserDialog as KritzelCurrentUserDialogElement } from "../../../../kritzel-stencil/dist/components/kritzel-current-user-dialog.js";
import { KritzelDialog as KritzelDialogElement } from "../../../../kritzel-stencil/dist/components/kritzel-dialog.js";
import { KritzelEditor as KritzelEditorElement } from "../../../../kritzel-stencil/dist/components/kritzel-editor.js";
import { KritzelExport as KritzelExportElement } from "../../../../kritzel-stencil/dist/components/kritzel-export.js";
import { KritzelInput as KritzelInputElement } from "../../../../kritzel-stencil/dist/components/kritzel-input.js";
import { KritzelLineEndings as KritzelLineEndingsElement } from "../../../../kritzel-stencil/dist/components/kritzel-line-endings.js";
import { KritzelLoginDialog as KritzelLoginDialogElement } from "../../../../kritzel-stencil/dist/components/kritzel-login-dialog.js";
import { KritzelMasterDetail as KritzelMasterDetailElement } from "../../../../kritzel-stencil/dist/components/kritzel-master-detail.js";
import { KritzelNumericInput as KritzelNumericInputElement } from "../../../../kritzel-stencil/dist/components/kritzel-numeric-input.js";
import { KritzelOpacitySlider as KritzelOpacitySliderElement } from "../../../../kritzel-stencil/dist/components/kritzel-opacity-slider.js";
import { KritzelPillTabs as KritzelPillTabsElement } from "../../../../kritzel-stencil/dist/components/kritzel-pill-tabs.js";
import { KritzelSettings as KritzelSettingsElement } from "../../../../kritzel-stencil/dist/components/kritzel-settings.js";
export type KritzelAwarenessCursorsEvents = NonNullable<unknown>;
export declare const KritzelAwarenessCursors: StencilReactComponent<KritzelAwarenessCursorsElement, KritzelAwarenessCursorsEvents, Components.KritzelAwarenessCursors>;
export type KritzelBackToContentEvents = {
    onBackToContent: EventName<KritzelBackToContentCustomEvent<void>>;
};
export declare const KritzelBackToContent: StencilReactComponent<KritzelBackToContentElement, KritzelBackToContentEvents, Components.KritzelBackToContent>;
export type KritzelButtonEvents = {
    onButtonClick: EventName<KritzelButtonCustomEvent<void>>;
};
export declare const KritzelButton: StencilReactComponent<KritzelButtonElement, KritzelButtonEvents, Components.KritzelButton>;
export type KritzelCurrentUserDialogEvents = NonNullable<unknown>;
export declare const KritzelCurrentUserDialog: StencilReactComponent<KritzelCurrentUserDialogElement, KritzelCurrentUserDialogEvents, Components.KritzelCurrentUserDialog>;
export type KritzelDialogEvents = {
    onDialogOpen: EventName<KritzelDialogCustomEvent<void>>;
    onDialogClose: EventName<KritzelDialogCustomEvent<IKritzelDialogCloseEvent>>;
};
export declare const KritzelDialog: StencilReactComponent<KritzelDialogElement, KritzelDialogEvents, Components.KritzelDialog>;
export type KritzelEditorEvents = {
    onIsReady: EventName<KritzelEditorCustomEvent<EditorIsReadyEvent>>;
    onActiveWorkspaceChange: EventName<KritzelEditorCustomEvent<ActiveWorkspaceChangeEvent>>;
    onObjectsChange: EventName<KritzelEditorCustomEvent<KritzelBaseObject[]>>;
    onObjectsAdded: EventName<KritzelEditorCustomEvent<ObjectsAddedEvent>>;
    onObjectsRemoved: EventName<KritzelEditorCustomEvent<ObjectsRemovedEvent>>;
    onObjectsUpdated: EventName<KritzelEditorCustomEvent<ObjectsUpdatedEvent>>;
    onUndoStateChange: EventName<KritzelEditorCustomEvent<KritzelUndoState>>;
    onThemeChange: EventName<KritzelEditorCustomEvent<ThemeName>>;
    onViewportChange: EventName<KritzelEditorCustomEvent<KritzelViewportState>>;
    onLogout: EventName<KritzelEditorCustomEvent<void>>;
    onLogin: EventName<KritzelEditorCustomEvent<LoginEvent>>;
    onIsPublicChange: EventName<KritzelEditorCustomEvent<IKritzelIsPublicChangedEvent>>;
    onAwarenessChange: EventName<KritzelEditorCustomEvent<Map<number, Record<string, any>>>>;
};
export declare const KritzelEditor: StencilReactComponent<KritzelEditorElement, KritzelEditorEvents, Components.KritzelEditor>;
export type KritzelExportEvents = {
    onExportPng: EventName<KritzelExportCustomEvent<void>>;
    onExportSvg: EventName<KritzelExportCustomEvent<void>>;
    onExportJson: EventName<KritzelExportCustomEvent<string>>;
};
export declare const KritzelExport: StencilReactComponent<KritzelExportElement, KritzelExportEvents, Components.KritzelExport>;
export type KritzelInputEvents = {
    onValueChange: EventName<KritzelInputCustomEvent<string>>;
};
export declare const KritzelInput: StencilReactComponent<KritzelInputElement, KritzelInputEvents, Components.KritzelInput>;
export type KritzelLineEndingsEvents = {
    onValueChange: EventName<KritzelLineEndingsCustomEvent<LineArrowConfig>>;
};
export declare const KritzelLineEndings: StencilReactComponent<KritzelLineEndingsElement, KritzelLineEndingsEvents, Components.KritzelLineEndings>;
export type KritzelLoginDialogEvents = {
    onProviderLogin: EventName<KritzelLoginDialogCustomEvent<LoginEvent>>;
    onDialogClosed: EventName<KritzelLoginDialogCustomEvent<void>>;
};
export declare const KritzelLoginDialog: StencilReactComponent<KritzelLoginDialogElement, KritzelLoginDialogEvents, Components.KritzelLoginDialog>;
export type KritzelMasterDetailEvents = {
    onItemSelect: EventName<KritzelMasterDetailCustomEvent<IKritzelMasterDetailSelectEvent>>;
};
export declare const KritzelMasterDetail: StencilReactComponent<KritzelMasterDetailElement, KritzelMasterDetailEvents, Components.KritzelMasterDetail>;
export type KritzelNumericInputEvents = {
    onValueChange: EventName<KritzelNumericInputCustomEvent<number | undefined>>;
};
export declare const KritzelNumericInput: StencilReactComponent<KritzelNumericInputElement, KritzelNumericInputEvents, Components.KritzelNumericInput>;
export type KritzelOpacitySliderEvents = {
    onValueChange: EventName<KritzelOpacitySliderCustomEvent<number>>;
};
export declare const KritzelOpacitySlider: StencilReactComponent<KritzelOpacitySliderElement, KritzelOpacitySliderEvents, Components.KritzelOpacitySlider>;
export type KritzelPillTabsEvents = {
    onValueChange: EventName<KritzelPillTabsCustomEvent<string>>;
};
export declare const KritzelPillTabs: StencilReactComponent<KritzelPillTabsElement, KritzelPillTabsEvents, Components.KritzelPillTabs>;
export type KritzelSettingsEvents = {
    onSettingsChange: EventName<KritzelSettingsCustomEvent<KritzelSettingsConfig>>;
};
export declare const KritzelSettings: StencilReactComponent<KritzelSettingsElement, KritzelSettingsEvents, Components.KritzelSettings>;
